
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"temp.h"
#include"uart.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint8_t temp, hum;

    UartInit(9600);
    delay_ms(1000);

    while (1)
    {
        if (DHT_read(&temp, &hum))
        {
        	char buffer[64];
        	    sprintf(buffer, "Temperature: %d C, Hum: %d %%\r\n", temp, hum);
        	    UartPuts(buffer);


        }
        delay_ms(15000);
    }
}
